import { Config, StatusOption } from "./types";
// todo add error boundary
import { z } from "zod";

const USERS_COLLECTION = 'users';

const ROLES = {
  ADMIN: "admin",
  MECHANIC: "mechanic",
  ELECTRICIAN: "electrician",
  WHEEL_ALIGNMENT: "wheelAlignment",
  ENGINE_MECHANIC: "engineMechanic",
  TIRE_SERVICE: "tireService",
  GENERATOR: "generator_starter",
  STO: "STO",
};

const appAccessRoles = [ROLES.ADMIN, ROLES.MECHANIC];

const optionRoles = [
  ROLES.MECHANIC,
  ROLES.ELECTRICIAN,
  ROLES.WHEEL_ALIGNMENT,
  ROLES.ENGINE_MECHANIC,
  ROLES.TIRE_SERVICE,
  ROLES.GENERATOR,
  ROLES.STO,
];

const STATUS_OPTIONS: StatusOption[] = [
  {
    value: "Incoming",
    editableBy: appAccessRoles,
    visibleBy: appAccessRoles,
  },
  {
    value: "Completed",
    editableBy: [ROLES.ADMIN],
    visibleBy: [ROLES.ADMIN],
  },
];

const STO: Config = {
  appName: "AutoRepairPro",
  mainCollection: "repair-orders",
  theme: {
    primaryColor: "#2c3e50",
    secondaryColor: "#e74c3c",
  },
  defaultRole: ROLES.MECHANIC,
  roles: appAccessRoles,
  statuses: ["Incoming", "Completed"],
  screens: [
    {
      name: "RepairOrdersBoard",
      type: "board",
      collection: "repair_orders",
      roles: [ROLES.ADMIN, ROLES.MECHANIC],
      defaultPresentation: "horizontal",
      statusOptions: STATUS_OPTIONS,
      filters: [
        {
          field: "dateCreated",
          type: "date",
          label: "По дате",
        },
      ],
    },
    {
      name: "MechanicsList",
      type: "list",
      collection: "mechanics",
      roles: [ROLES.ADMIN],
      icon: "account-hard-hat",
      presentation: "table",
    },
    {
      name: "CustomersList",
      type: "list",
      collection: "customers",
      roles: [ROLES.ADMIN],
      icon: "account-multiple",
      presentation: "table",
      filters: [
        {
          field: "fullName",
          type: "search",
          label: "Поиск клиентов",
          searchTermKeys: ["fullName", "phone", "email"],
        },
      ],
    },
    {
      name: "VehiclesList",
      type: "list",
      collection: "vehicles",
      roles: [ROLES.ADMIN],
      icon: "car",
      presentation: "table",
      filters: [
        {
          field: "licensePlate",
          type: "search",
          label: "by car number",
          searchTermKeys: ["licensePlate", "model"],
        },
        {
          field: "createdAt",
          type: "date",
          label: "По дате",
        },
      ],
    },
    {
      name: "ServicesList",
      type: "list",
      collection: "repair_services",
      roles: [ROLES.ADMIN],
      icon: "tools",
      presentation: "table",
      orderBy: ["name"],
    },
    {
      name: "InventoryList",
      type: "list",
      collection: "inventory",
      roles: [ROLES.ADMIN],
      presentation: "table",
      icon: "package-variant",
    },
    {
      name: "ExpensesList",
      type: "list",
      collection: "expenses",
      roles: [ROLES.ADMIN],
      icon: "cash-minus",
      presentation: "table",
      filters: [
        {
          field: "date",
          type: "date",
          label: "По дате",
        },
        {
          field: "text",
          type: "search",
          label: "Поиск расходов",
          searchTermKeys: ["text"],
        },
      ],
    },
    {
      name: "STOReportsScreen",
      type: "reports",
      collection: "repair_orders",
      roles: [ROLES.ADMIN],
    },
    {
      name: "MakesList",
      type: "list",
      collection: "makes",
      roles: [ROLES.ADMIN],
      icon: "car",
      presentation: "table",
      filters: [
        {
          field: "name",
          type: "search",
          label: "Search Makes",
          searchTermKeys: ["name"],
        },
      ],
    },
    // {
    //   name: "CustomerChat",
    //   type: "chat",
    //   collection: "customer_chats",
    //   roles: [ROLES.ADMIN],
    // },
  ],
  database: {
    collections: [
      {
        name: "mechanics",
        fields: [
          {
            name: "fullName",
            type: "text",
            label: "Full Name",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
            validation: z.string().min(1, { message: "Поле не должно быть пустым" }).optional(),
          },
          {
            name: "phone",
            type: "phone",
            label: "Phone Number",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "email",
            type: "text",
            label: "Email",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: false,
          },
          {
            name: "role",
            type: "dropdown",
            label: "Role",
            options: optionRoles,
            required: true,
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
        ],
      },
      {
        name: "repair_orders",
        uniqIdNumber: true,
        fields: [
          {
            name: "numberId",
            type: "numberId",
            label: "Order Number",
            list: [],
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [],
            width: 0.3,
          },
          {
            name: "status",
            type: "dropdown",
            options: ["Incoming", "Completed"],
            label: "Status",
            defaultValue: "Incoming",
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            formCreate: [],
            formEdit: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [],
          },
          {
            name: "dateCreated",
            type: "dateTime",
            label: "dateCreated",
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            formEdit: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
          },
          {
            name: "statusChangedAt",
            type: "dateTime",
            label: "Время изменения статуса",
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
          },
          {
            name: "vehicle",
            type: "collectionPicker",
            collection: "vehicles",
            label: "Vehicle",
            key: "licensePlate",
            secondKey: "make.name",
            thirdKey: "model",
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
            required: true,
          },
          {
            name: "mechanics",
            type: "mechanicPicker",
            label: "Services",
            collection: "mechanics",
            key: "fullName",
            relatedObject: {
              countTotal: true,
              formula:
                "contextData.reduce((sum, current) => sum + parseInt(current.price), 0)",
              collection: "repair_services",
              key: "name",
              secondKey: "price",
              multiselect: true,
              where: [
                {
                  field: "roles",
                  value: "role",
                  from: "formData",
                },
              ],
            },
            // collection: "repair_services",
            // secondKey: "role",
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
            required: true,
          },
          {
            name: "parts",
            type: "testPicker",
            label: "Parts",
            collection: "mechanics",
            key: "fullName",
            // secondKey: "role",
            relatedObject: {
              formula:
                "contextData.reduce((sum, current) => sum + parseInt(current.price), 0)",
              collection: "inventory",
              key: "name",
              secondKey: "price",
              multiselect: true,
            },
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
          },
          {
            name: "totalPrice",
            type: "calculated",
            label: "Total Price",
            calculation: {
              formula:
                "(mechanics || []).reduce((sum, item) => sum + ((item?.relatedObjectField || []).reduce((s, el) => s + (parseFloat(el?.price) || 0), 0)), 0) + (parts || []).reduce((sum, item) => sum + ((item?.relatedObjectField || []).reduce((s, el) => s + (parseFloat(el?.price) || 0), 0)), 0)",
              dependencies: ["mechanics", "parts"],
            },
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
          },
          // {
          //   name: "mechanic",
          //   type: "collectionPicker",
          //   collection: "mechanics",
          //   label: "Mechanic",
          //   key: "fullName",
          //   list: ["admin"],
          //   form: ["admin"],
          //   board: ["admin"],
          //   required: true,
          // },
          {
            name: "payments",
            type: "paymentsForm",
            options: ["cash", "halyk", "kaspi"],
            label: "Payments",
            list: [],
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [],
            required: true,
          },
          {
            name: "unpaidAmount",
            type: "calculated",
            label: "Remaining Amount",
            calculation: {
              formula:
                "Number(totalPrice[0]) - payments.reduce((sum, p) => sum + Number(p.paymentAmount), 0)",
              dependencies: ["totalPrice", "payments"],
            },
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [ROLES.ADMIN, ROLES.MECHANIC],
          },
          {
            name: "notes",
            type: "textarea",
            label: "Notes",
            list: [ROLES.ADMIN, ROLES.MECHANIC],
            form: [ROLES.ADMIN, ROLES.MECHANIC],
            board: [],
          },
        ],
      },
      {
        name: "payments",
        fields: [
          {
            name: "paymentType",
            type: "dropdown",
            options: ["cash", "halyk", "kaspi"],
            label: "Payment Method",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
          {
            name: "paymentAmount",
            type: "number",
            label: "paymentAmount",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: []
          },
        ],
      },
      {
        name: "customers",
        fields: [
          {
            name: "fullName",
            type: "text",
            label: "Full Name",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "phone",
            type: "phone",
            label: "Phone Number",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "email",
            type: "text",
            label: "Email",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
          {
            name: "address",
            type: "text",
            label: "Address",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
        ],
      },
      {
        name: "vehicles",
        fields: [
          {
            name: "make",
            type: "collectionPicker",
            collection: "makes",
            label: "Make",
            key: "name",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "model",
            type: "text",
            label: "Model",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "licensePlate",
            type: "text",
            label: "License Plate",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "year",
            type: "text",
            label: "Year",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: false,
          },
          {
            name: "vin",
            type: "text",
            label: "VIN",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
          {
            name: "owner",
            type: "collectionPicker",
            collection: "customers",
            label: "Owner",
            key: "fullName",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
        ],
      },
      {
        name: "repair_services",
        fields: [
          {
            name: "name",
            type: "text",
            label: "Service Name",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "description",
            type: "textarea",
            label: "Description",
            list: [],
            form: [ROLES.ADMIN],
            board: [],
          },
          {
            name: "price",
            type: "number",
            label: "Price",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
            width: 0.4,
          },
          {
            name: "duration",
            type: "number",
            label: "Duration (hours)",
            list: [],
            form: [ROLES.ADMIN],
            board: [],
          },
          {
            name: "roles",
            type: "dropdown",
            label: "Roles",
            multiselect: true,
            options: optionRoles,
            required: true,
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
        ],
      },
      {
        name: "inventory",
        fields: [
          {
            name: "name",
            type: "text",
            label: "Part Name",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "description",
            type: "textarea",
            label: "Description",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
          {
            name: "price",
            type: "number",
            label: "Price",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "quantity",
            type: "number",
            label: "Quantity in Stock",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
          {
            name: "location",
            type: "text",
            label: "Storage Location",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
          },
        ],
      },
      {
        name: "expenses",
        uniqIdNumber: true,
        fields: [
          {
            name: "numberId",
            type: "numberId",
            label: "#",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
            width: 0.3,
          },
          {
            name: "date",
            type: "datePicker",
            label: "Date",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
            required: true,
          },
          {
            name: "text",
            type: "text",
            label: "Description",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
            required: true,
          },
          {
            name: "amount",
            type: "number",
            label: "Amount",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
            required: true,
          },
        ],
      },
      {
        name: USERS_COLLECTION,
        fields: [
          {
            name: "role",
            type: "dropdown",
            label: "Role",
            options: appAccessRoles,
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
          },
          {
            name: "email",
            type: "text",
            label: "Email",
            readOnly: true,
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
          },
          {
            name: "fullName",
            type: "text",
            label: "Full name",
            readOnly: true,
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [ROLES.ADMIN],
          },
        ],
      },
      {
        name: "makes",
        fields: [
          {
            name: "name",
            type: "text",
            label: "Make Name",
            list: [ROLES.ADMIN],
            form: [ROLES.ADMIN],
            board: [],
            required: true,
          },
        ],
      },
    ],
  },
};

export default STO;
